// <auto-generated />
namespace Vidly.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class populate_birthdays : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(populate_birthdays));
        
        string IMigrationMetadata.Id
        {
            get { return "202004021731566_populate_birthdays"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
