// <auto-generated />
namespace Vidly.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class dateTime_fields_in_Movies_change_To_dateTime2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(dateTime_fields_in_Movies_change_To_dateTime2));
        
        string IMigrationMetadata.Id
        {
            get { return "202004090800549_dateTime_fields_in_Movies_change_To_dateTime2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
