// <auto-generated />
namespace Vidly.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class change_dates_on_movies_in_DB : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(change_dates_on_movies_in_DB));
        
        string IMigrationMetadata.Id
        {
            get { return "202004030958522_change_dates_on_movies_in_DB"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
